ls:
  packages/*/{src,__tests__}:
    .js: camelCase | PascalCase
    .test.js: camelCase | PascalCase
    .ts: camelCase | PascalCase
    .d.ts: camelCase
    .spec.ts: camelCase | PascalCase
    .mock.ts: camelCase

ignore:
  - node_modules
